Update patches

diff --git a/Patches-opensim/compile_deps b/Patches-opensim/compile_deps
--- a/Patches-opensim/compile_deps
+++ b/Patches-opensim/compile_deps
@@ -6,8 +6,13 @@ set -e
 BUILD_TYPE="Release"
 MOCO="ON"
 TESTING="OFF"
+NUM_JOBS=8
 
-#  swig moet versie 4.1.1 zijn.
+# Install dependencies from package manager.
+echo "LOG: INSTALLING DEPENDENCIES..."
+sudo apt-get update && sudo apt-get install --yes build-essential cmake autotools-dev autoconf pkg-config automake libopenblas-dev liblapack-dev freeglut3-dev libxi-dev libxmu-dev doxygen python3 python3-dev python3-numpy python3-setuptools git libssl-dev libpcre2-dev libtool gfortran ninja-build patchelf || ( echo "Installation of dependencies using apt-get failed." && exit )
+
+#  swig moet versie 4.1.1 zijn.  (installed from source)
 
 # change this for a different location
 OPENSIM_DIR=/home/sietse/Software/OpenSim
@@ -23,13 +28,13 @@ export SIMBODY_HOME=/usr/local
 
 cd build_simbody
 cmake ../simbody -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_TESTING=${TESTING}
-make -j8
+make -j$NUN_JOBS
 sudo make install
 
 cd ${OPENSIM_DIR}/build_deps
 cmake ../opensim-core/dependencies -DCMAKE_INSTALL_PREFIX=${OPENSIM_DIR}/opensim_dependencies_install  -DSUPERBUILD_ezc3d=ON -DOPENSIM_WITH_TROPTER=$MOCO -DOPENSIM_WITH_CASADI=$MOCO -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DSUPERBUILD_simbody=OFF
 cmake . -LAH
-cmake --build . --config Release
+cmake --build . --config Release -j$NUM_JOBS
 
 echo ==== done  getdeps ====
 
